[build]
  publish = "dist/photobook"
  command = "ng build --configuration production"

[functions]
  directory = "netlify/functions" # Thư mục chứa các hàm (nếu có)

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
